image:
  repository: flybywiresim/do-download-counter
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  port: 3000

ingress:
  fqdn: ~
  tls:
    enabled: false
    issuer: ~

database:
  host: ~
  port: 3306
  database: fbw
  user: fbw
  password: somePassword

urlPrefixes: https://your-url
installerUrl: https://your-url
